// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: getdice.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReleaseGetDiceYmlRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReleaseGetDiceYmlRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReleaseGetDiceYmlRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReleaseGetDiceYmlRequestMultiError, or nil if none found.
func (m *ReleaseGetDiceYmlRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReleaseGetDiceYmlRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReleaseID

	if len(errors) > 0 {
		return ReleaseGetDiceYmlRequestMultiError(errors)
	}

	return nil
}

// ReleaseGetDiceYmlRequestMultiError is an error wrapping multiple validation
// errors returned by ReleaseGetDiceYmlRequest.ValidateAll() if the designated
// constraints aren't met.
type ReleaseGetDiceYmlRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReleaseGetDiceYmlRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReleaseGetDiceYmlRequestMultiError) AllErrors() []error { return m }

// ReleaseGetDiceYmlRequestValidationError is the validation error returned by
// ReleaseGetDiceYmlRequest.Validate if the designated constraints aren't met.
type ReleaseGetDiceYmlRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReleaseGetDiceYmlRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReleaseGetDiceYmlRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReleaseGetDiceYmlRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReleaseGetDiceYmlRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReleaseGetDiceYmlRequestValidationError) ErrorName() string {
	return "ReleaseGetDiceYmlRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReleaseGetDiceYmlRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReleaseGetDiceYmlRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReleaseGetDiceYmlRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReleaseGetDiceYmlRequestValidationError{}

// Validate checks the field values on ReleaseGetDiceYmlResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReleaseGetDiceYmlResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReleaseGetDiceYmlResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReleaseGetDiceYmlResponseMultiError, or nil if none found.
func (m *ReleaseGetDiceYmlResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReleaseGetDiceYmlResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Data

	if len(errors) > 0 {
		return ReleaseGetDiceYmlResponseMultiError(errors)
	}

	return nil
}

// ReleaseGetDiceYmlResponseMultiError is an error wrapping multiple validation
// errors returned by ReleaseGetDiceYmlResponse.ValidateAll() if the
// designated constraints aren't met.
type ReleaseGetDiceYmlResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReleaseGetDiceYmlResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReleaseGetDiceYmlResponseMultiError) AllErrors() []error { return m }

// ReleaseGetDiceYmlResponseValidationError is the validation error returned by
// ReleaseGetDiceYmlResponse.Validate if the designated constraints aren't met.
type ReleaseGetDiceYmlResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReleaseGetDiceYmlResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReleaseGetDiceYmlResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReleaseGetDiceYmlResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReleaseGetDiceYmlResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReleaseGetDiceYmlResponseValidationError) ErrorName() string {
	return "ReleaseGetDiceYmlResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReleaseGetDiceYmlResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReleaseGetDiceYmlResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReleaseGetDiceYmlResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReleaseGetDiceYmlResponseValidationError{}
