// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: msp.proto

package pb

import (
	bytes "bytes"
	json "encoding/json"

	jsonpb "github.com/erda-project/erda-infra/pkg/transport/http/encoding/jsonpb"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*MONITOR_INSTANCES_Request)(nil)
var _ json.Unmarshaler = (*MONITOR_INSTANCES_Request)(nil)
var _ json.Marshaler = (*MONITOR_RUNTIME_Request)(nil)
var _ json.Unmarshaler = (*MONITOR_RUNTIME_Request)(nil)

// MONITOR_INSTANCES_Request implement json.Marshaler.
func (m *MONITOR_INSTANCES_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// MONITOR_INSTANCES_Request implement json.Marshaler.
func (m *MONITOR_INSTANCES_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// MONITOR_RUNTIME_Request implement json.Marshaler.
func (m *MONITOR_RUNTIME_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// MONITOR_RUNTIME_Request implement json.Marshaler.
func (m *MONITOR_RUNTIME_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}
