// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Source: graph.proto

package pb

import (
	context "context"
	http1 "net/http"

	transport "github.com/erda-project/erda-infra/pkg/transport"
	http "github.com/erda-project/erda-infra/pkg/transport/http"
	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/transport/http" package it is being compiled against.
const _ = http.SupportPackageIsVersion1

// GraphServiceHandler is the server API for GraphService service.
type GraphServiceHandler interface {
	// POST /api/pipelines/actions/pipeline-yml-graph
	PipelineYmlGraph(context.Context, *PipelineYmlGraphRequest) (*PipelineYmlGraphResponse, error)
}

// RegisterGraphServiceHandler register GraphServiceHandler to http.Router.
func RegisterGraphServiceHandler(r http.Router, srv GraphServiceHandler, opts ...http.HandleOption) {
	h := http.DefaultHandleOptions()
	for _, op := range opts {
		op(h)
	}
	encodeFunc := func(fn func(http1.ResponseWriter, *http1.Request) (interface{}, error)) http.HandlerFunc {
		handler := func(w http1.ResponseWriter, r *http1.Request) {
			out, err := fn(w, r)
			if err != nil {
				h.Error(w, r, err)
				return
			}
			if err := h.Encode(w, r, out); err != nil {
				h.Error(w, r, err)
			}
		}
		if h.HTTPInterceptor != nil {
			handler = h.HTTPInterceptor(handler)
		}
		return handler
	}

	add_PipelineYmlGraph := func(method, path string, fn func(context.Context, *PipelineYmlGraphRequest) (*PipelineYmlGraphResponse, error)) {
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return fn(ctx, req.(*PipelineYmlGraphRequest))
		}
		var PipelineYmlGraph_info transport.ServiceInfo
		if h.Interceptor != nil {
			PipelineYmlGraph_info = transport.NewServiceInfo("erda.core.pipeline.graph.GraphService", "PipelineYmlGraph", srv)
			handler = h.Interceptor(handler)
		}
		r.Add(method, path, encodeFunc(
			func(w http1.ResponseWriter, r *http1.Request) (interface{}, error) {
				ctx := http.WithRequest(r.Context(), r)
				ctx = transport.WithHTTPHeaderForServer(ctx, r.Header)
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, PipelineYmlGraph_info)
				}
				r = r.WithContext(ctx)
				var in PipelineYmlGraphRequest
				if err := h.Decode(r, &in); err != nil {
					return nil, err
				}
				var input interface{} = &in
				if u, ok := (input).(urlenc.URLValuesUnmarshaler); ok {
					if err := u.UnmarshalURLValues("", r.URL.Query()); err != nil {
						return nil, err
					}
				}
				out, err := handler(ctx, &in)
				if err != nil {
					return out, err
				}
				return out, nil
			}),
		)
	}

	add_PipelineYmlGraph("POST", "/api/pipelines/actions/pipeline-yml-graph", srv.PipelineYmlGraph)
}
