// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: msp_apm_trace.proto

package pb

import (
	bytes "bytes"
	json "encoding/json"

	jsonpb "github.com/erda-project/erda-infra/pkg/transport/http/encoding/jsonpb"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*GET_SPANS_Request)(nil)
var _ json.Unmarshaler = (*GET_SPANS_Request)(nil)
var _ json.Marshaler = (*GET_TRACE_CONDITIONS_LIST_Request)(nil)
var _ json.Unmarshaler = (*GET_TRACE_CONDITIONS_LIST_Request)(nil)
var _ json.Marshaler = (*GET_TRACE_DEBUG_HISTORIES_Request)(nil)
var _ json.Unmarshaler = (*GET_TRACE_DEBUG_HISTORIES_Request)(nil)
var _ json.Marshaler = (*GET_TRACE_DEBUG_HISTORY_STATUS_Request)(nil)
var _ json.Unmarshaler = (*GET_TRACE_DEBUG_HISTORY_STATUS_Request)(nil)
var _ json.Marshaler = (*GET_TRACE_LIST_Request)(nil)
var _ json.Unmarshaler = (*GET_TRACE_LIST_Request)(nil)
var _ json.Marshaler = (*LIST_TRACE_DEBUG_HISTORIES_Request)(nil)
var _ json.Unmarshaler = (*LIST_TRACE_DEBUG_HISTORIES_Request)(nil)
var _ json.Marshaler = (*POST_TRACE_DEBUG_HISTORIES_Request)(nil)
var _ json.Unmarshaler = (*POST_TRACE_DEBUG_HISTORIES_Request)(nil)
var _ json.Marshaler = (*PUT_TRACE_DEBUG_HISTORY_STOP_Request)(nil)
var _ json.Unmarshaler = (*PUT_TRACE_DEBUG_HISTORY_STOP_Request)(nil)

// GET_SPANS_Request implement json.Marshaler.
func (m *GET_SPANS_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GET_SPANS_Request implement json.Marshaler.
func (m *GET_SPANS_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GET_TRACE_CONDITIONS_LIST_Request implement json.Marshaler.
func (m *GET_TRACE_CONDITIONS_LIST_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GET_TRACE_CONDITIONS_LIST_Request implement json.Marshaler.
func (m *GET_TRACE_CONDITIONS_LIST_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GET_TRACE_DEBUG_HISTORIES_Request implement json.Marshaler.
func (m *GET_TRACE_DEBUG_HISTORIES_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GET_TRACE_DEBUG_HISTORIES_Request implement json.Marshaler.
func (m *GET_TRACE_DEBUG_HISTORIES_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GET_TRACE_DEBUG_HISTORY_STATUS_Request implement json.Marshaler.
func (m *GET_TRACE_DEBUG_HISTORY_STATUS_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GET_TRACE_DEBUG_HISTORY_STATUS_Request implement json.Marshaler.
func (m *GET_TRACE_DEBUG_HISTORY_STATUS_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GET_TRACE_LIST_Request implement json.Marshaler.
func (m *GET_TRACE_LIST_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GET_TRACE_LIST_Request implement json.Marshaler.
func (m *GET_TRACE_LIST_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// LIST_TRACE_DEBUG_HISTORIES_Request implement json.Marshaler.
func (m *LIST_TRACE_DEBUG_HISTORIES_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// LIST_TRACE_DEBUG_HISTORIES_Request implement json.Marshaler.
func (m *LIST_TRACE_DEBUG_HISTORIES_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// POST_TRACE_DEBUG_HISTORIES_Request implement json.Marshaler.
func (m *POST_TRACE_DEBUG_HISTORIES_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// POST_TRACE_DEBUG_HISTORIES_Request implement json.Marshaler.
func (m *POST_TRACE_DEBUG_HISTORIES_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// PUT_TRACE_DEBUG_HISTORY_STOP_Request implement json.Marshaler.
func (m *PUT_TRACE_DEBUG_HISTORY_STOP_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// PUT_TRACE_DEBUG_HISTORY_STOP_Request implement json.Marshaler.
func (m *PUT_TRACE_DEBUG_HISTORY_STOP_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}
