// Code generated by protoc-gen-go-client. DO NOT EDIT.
// Sources: pipeline.proto

package client

import (
	fmt "fmt"
	reflect "reflect"
	strings "strings"

	servicehub "github.com/erda-project/erda-infra/base/servicehub"
	grpc "github.com/erda-project/erda-infra/pkg/transport/grpc"
	pb "github.com/erda-project/erda-proto-go/core/pipeline/pipeline/pb"
	grpc1 "google.golang.org/grpc"
)

var dependencies = []string{
	"grpc-client@erda.core.pipeline.pipeline",
	"grpc-client",
}

// +provider
type provider struct {
	client Client
}

func (p *provider) Init(ctx servicehub.Context) error {
	var conn grpc.ClientConnInterface
	for _, dep := range dependencies {
		c, ok := ctx.Service(dep).(grpc.ClientConnInterface)
		if ok {
			conn = c
			break
		}
	}
	if conn == nil {
		return fmt.Errorf("not found connector in (%s)", strings.Join(dependencies, ", "))
	}
	p.client = New(conn)
	return nil
}

var (
	clientsType               = reflect.TypeOf((*Client)(nil)).Elem()
	pipelineServiceClientType = reflect.TypeOf((*pb.PipelineServiceClient)(nil)).Elem()
	pipelineServiceServerType = reflect.TypeOf((*pb.PipelineServiceServer)(nil)).Elem()
)

func (p *provider) Provide(ctx servicehub.DependencyContext, args ...interface{}) interface{} {
	var opts []grpc1.CallOption
	for _, arg := range args {
		if opt, ok := arg.(grpc1.CallOption); ok {
			opts = append(opts, opt)
		}
	}
	switch ctx.Service() {
	case "erda.core.pipeline.pipeline-client":
		return p.client
	case "erda.core.pipeline.pipeline.PipelineService":
		return &pipelineServiceWrapper{client: p.client.PipelineService(), opts: opts}
	case "erda.core.pipeline.pipeline.PipelineService.client":
		return p.client.PipelineService()
	}
	switch ctx.Type() {
	case clientsType:
		return p.client
	case pipelineServiceClientType:
		return p.client.PipelineService()
	case pipelineServiceServerType:
		return &pipelineServiceWrapper{client: p.client.PipelineService(), opts: opts}
	}
	return p
}

func init() {
	servicehub.Register("erda.core.pipeline.pipeline-client", &servicehub.Spec{
		Services: []string{
			"erda.core.pipeline.pipeline.PipelineService",
			"erda.core.pipeline.pipeline.PipelineService.client",
			"erda.core.pipeline.pipeline-client",
		},
		Types: []reflect.Type{
			clientsType,
			// client types
			pipelineServiceClientType,
			// server types
			pipelineServiceServerType,
		},
		OptionalDependencies: dependencies,
		Creator: func() servicehub.Provider {
			return &provider{}
		},
	})
}
