// Code generated by protoc-gen-go-form. DO NOT EDIT.
// Source: officer.proto

package pb

import (
	url "net/url"
	strconv "strconv"

	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/urlenc" package it is being compiled against.
var _ urlenc.URLValuesUnmarshaler = (*OFFICER_FETCH_SCRIPT_Request)(nil)
var _ urlenc.URLValuesUnmarshaler = (*OFFICER_GET_PRICE_Request)(nil)
var _ urlenc.URLValuesUnmarshaler = (*OFFICER_GET_SCRIPT_INFO_Request)(nil)
var _ urlenc.URLValuesUnmarshaler = (*ScriptInfo)(nil)

// OFFICER_FETCH_SCRIPT_Request implement urlenc.URLValuesUnmarshaler.
func (m *OFFICER_FETCH_SCRIPT_Request) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "name":
				m.Name = vals[0]
			}
		}
	}
	return nil
}

// OFFICER_GET_PRICE_Request implement urlenc.URLValuesUnmarshaler.
func (m *OFFICER_GET_PRICE_Request) UnmarshalURLValues(prefix string, values url.Values) error {
	return nil
}

// OFFICER_GET_SCRIPT_INFO_Request implement urlenc.URLValuesUnmarshaler.
func (m *OFFICER_GET_SCRIPT_INFO_Request) UnmarshalURLValues(prefix string, values url.Values) error {
	return nil
}

// ScriptInfo implement urlenc.URLValuesUnmarshaler.
func (m *ScriptInfo) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "md5":
				m.Md5 = vals[0]
			case "name":
				m.Name = vals[0]
			case "size":
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Size = val
			case "scriptBlackList":
				m.ScriptBlackList = vals
			}
		}
	}
	return nil
}
