// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: msp_apm_log_service.proto

package pb

import (
	bytes "bytes"
	json "encoding/json"

	jsonpb "github.com/erda-project/erda-infra/pkg/transport/http/encoding/jsonpb"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*MSP_ADDON_LOGS_AGGREGATION_Request)(nil)
var _ json.Unmarshaler = (*MSP_ADDON_LOGS_AGGREGATION_Request)(nil)
var _ json.Marshaler = (*MSP_ADDON_LOGS_DOWNLOAD_Request)(nil)
var _ json.Unmarshaler = (*MSP_ADDON_LOGS_DOWNLOAD_Request)(nil)
var _ json.Marshaler = (*MSP_ADDON_LOGS_FIELDS_Request)(nil)
var _ json.Unmarshaler = (*MSP_ADDON_LOGS_FIELDS_Request)(nil)
var _ json.Marshaler = (*MSP_ADDON_LOGS_SEARCH_GET_Request)(nil)
var _ json.Unmarshaler = (*MSP_ADDON_LOGS_SEARCH_GET_Request)(nil)
var _ json.Marshaler = (*MSP_ADDON_LOGS_SEARCH_SEQUENTIAL_Request)(nil)
var _ json.Unmarshaler = (*MSP_ADDON_LOGS_SEARCH_SEQUENTIAL_Request)(nil)
var _ json.Marshaler = (*MSP_ADDON_LOGS_STATISTIC_Request)(nil)
var _ json.Unmarshaler = (*MSP_ADDON_LOGS_STATISTIC_Request)(nil)

// MSP_ADDON_LOGS_AGGREGATION_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_AGGREGATION_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// MSP_ADDON_LOGS_AGGREGATION_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_AGGREGATION_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// MSP_ADDON_LOGS_DOWNLOAD_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_DOWNLOAD_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// MSP_ADDON_LOGS_DOWNLOAD_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_DOWNLOAD_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// MSP_ADDON_LOGS_FIELDS_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_FIELDS_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// MSP_ADDON_LOGS_FIELDS_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_FIELDS_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// MSP_ADDON_LOGS_SEARCH_GET_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_SEARCH_GET_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// MSP_ADDON_LOGS_SEARCH_GET_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_SEARCH_GET_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// MSP_ADDON_LOGS_SEARCH_SEQUENTIAL_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_SEARCH_SEQUENTIAL_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// MSP_ADDON_LOGS_SEARCH_SEQUENTIAL_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_SEARCH_SEQUENTIAL_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// MSP_ADDON_LOGS_STATISTIC_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_STATISTIC_Request) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// MSP_ADDON_LOGS_STATISTIC_Request implement json.Marshaler.
func (m *MSP_ADDON_LOGS_STATISTIC_Request) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}
